version: '3.7'
services:
  csds:
    container_name: cs
    image: cs-dedicated-server:latest
    build: .
    ports:
      - 26900:26900/udp
      - 27020:27020/udp
      - 27015:27015/udp
      - 27015:27015/tcp
    env_file:
      - env.secret
    command:
      - +log
